# Generated by Django 6.0 on 2025-12-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rustdesdevice_ip_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rustdesdevice',
            options={'ordering': ('-rid',), 'verbose_name': '기기', 'verbose_name_plural': '기기 목록'},
        ),
        migrations.AlterModelOptions(
            name='rustdeskpeer',
            options={'ordering': ('-username',), 'verbose_name': 'Peers', 'verbose_name_plural': 'Peers 목록'},
        ),
        migrations.AlterModelOptions(
            name='rustdesktag',
            options={'ordering': ('-uid',), 'verbose_name': 'Tags', 'verbose_name_plural': 'Tags 목록'},
        ),
        migrations.AlterModelOptions(
            name='rustdesktoken',
            options={'ordering': ('-username',), 'verbose_name': 'Token', 'verbose_name_plural': 'Token 목록'},
        ),
        migrations.AlterModelOptions(
            name='sharelink',
            options={'ordering': ('-create_time',), 'verbose_name': '공유 링크', 'verbose_name_plural': '링크 목록'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_task', 'Can see available tasks'), ('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')), 'verbose_name': '사용자', 'verbose_name_plural': '사용자 목록'},
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='기기 등록 시간'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='hostname',
            field=models.CharField(max_length=100, verbose_name='호스트명'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='memory',
            field=models.CharField(max_length=100, verbose_name='메모리'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='os',
            field=models.CharField(max_length=100, verbose_name='운영체제'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='rid',
            field=models.CharField(blank=True, max_length=60, verbose_name='클라이언트 ID'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='기기 업데이트 시간'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='시스템 사용자명'),
        ),
        migrations.AlterField(
            model_name='rustdesdevice',
            name='version',
            field=models.CharField(max_length=100, verbose_name='클라이언트 버전'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='alias',
            field=models.CharField(max_length=30, verbose_name='별칭'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='hostname',
            field=models.CharField(max_length=30, verbose_name='운영체제명'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='platform',
            field=models.CharField(max_length=30, verbose_name='플랫폼'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='rhash',
            field=models.CharField(max_length=60, verbose_name='기기 연결 비밀번호'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='rid',
            field=models.CharField(max_length=60, verbose_name='클라이언트 ID'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='tags',
            field=models.CharField(max_length=30, verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='uid',
            field=models.CharField(max_length=16, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='rustdeskpeer',
            name='username',
            field=models.CharField(max_length=20, verbose_name='시스템 사용자명'),
        ),
        migrations.AlterField(
            model_name='rustdesktag',
            name='tag_color',
            field=models.CharField(blank=True, max_length=60, verbose_name='태그 색상'),
        ),
        migrations.AlterField(
            model_name='rustdesktag',
            name='tag_name',
            field=models.CharField(max_length=60, verbose_name='태그 이름'),
        ),
        migrations.AlterField(
            model_name='rustdesktag',
            name='uid',
            field=models.CharField(max_length=16, verbose_name='소유 사용자 ID'),
        ),
        migrations.AlterField(
            model_name='rustdesktoken',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='로그인 시간'),
        ),
        migrations.AlterField(
            model_name='rustdesktoken',
            name='uid',
            field=models.CharField(max_length=16, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='rustdesktoken',
            name='username',
            field=models.CharField(max_length=20, verbose_name='사용자명'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='만료 여부'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='사용 여부'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='peers',
            field=models.CharField(max_length=20, verbose_name='기기 ID 목록'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='shash',
            field=models.CharField(max_length=60, verbose_name='링크 Key'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='uid',
            field=models.CharField(max_length=16, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='deviceInfo',
            field=models.TextField(blank=True, verbose_name='로그인 정보:'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='관리자 여부'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='RustDesk ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rtype',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='rtype'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='사용자명'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='uuid'),
        ),
    ]
