# Generated by Django 6.0 on 2025-12-25 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_company_name_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rustdesktoken',
            name='rid',
            field=models.CharField(max_length=16, verbose_name='MDesk ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rid',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='MDesk ID'),
        ),
        migrations.CreateModel(
            name='CustomAppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='MDesk', max_length=100, verbose_name='앱 이름')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='custom_logos/', verbose_name='로고')),
                ('password', models.CharField(blank=True, default='', max_length=100, verbose_name='암호')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '커스텀 앱 설정',
                'verbose_name_plural': '커스텀 앱 설정 목록',
                'unique_together': {('uid',)},
            },
        ),
    ]
