# Generated by Django 6.0 on 2025-12-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_rustdesktoken_rid_alter_userprofile_rid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customappconfig',
            name='description',
            field=models.CharField(blank=True, default='Your desktop can be accessed with this ID and password.', max_length=500, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='customappconfig',
            name='title',
            field=models.CharField(blank=True, default='Your Desktop', max_length=200, verbose_name='제목'),
        ),
    ]
