# Generated by Django 6.0 on 2025-12-26 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customappconfig_description_customappconfig_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_num', models.IntegerField(verbose_name='상담원 번호')),
                ('agent_name', models.CharField(max_length=100, verbose_name='상담원 이름')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '상담원',
                'verbose_name_plural': '상담원 목록',
                'ordering': ['agent_num'],
                'unique_together': {('uid', 'agent_num')},
            },
        ),
    ]
