# Generated by Django 6.0 on 2025-12-26 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_supportagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConnectionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdesk_id', models.CharField(max_length=50, verbose_name='MDesk ID')),
                ('agent_num', models.IntegerField(verbose_name='상담원 번호')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='접속 시간')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '상담원 접속 기록',
                'verbose_name_plural': '상담원 접속 기록 목록',
                'ordering': ['-create_time'],
            },
        ),
    ]
