# Generated by Django 6.0 on 2025-12-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_agentconnectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customappconfig',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='전화번호'),
        ),
    ]
