# Generated by Django 6.0 on 2025-12-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_customappconfig_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customappconfig',
            name='url_nickname',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='URL 별명'),
        ),
    ]
