# Generated by Django 6.0 on 2025-12-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_customappconfig_url_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customappconfig',
            name='url_alias',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True, verbose_name='URL 별명'),
        ),
    ]
