# Generated by Django 6.0 on 2025-12-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_customappconfig_url_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customappconfig',
            name='url_alias',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_agents',
            field=models.IntegerField(default=3, verbose_name='최대 상담원 수'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_expires',
            field=models.DateField(blank=True, null=True, verbose_name='이용 만료일'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_level',
            field=models.CharField(choices=[('free', '무료'), ('basic', '기본'), ('standard', '스탠다드'), ('premium', '프리미엄'), ('enterprise', '엔터프라이즈')], default='free', max_length=20, verbose_name='회원 등급'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_start',
            field=models.DateField(blank=True, null=True, verbose_name='이용 시작일'),
        ),
    ]
