# Generated by Django 6.0 on 2025-12-29 15:07

import api.models_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_customappconfig_url_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customappconfig',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models_user.logo_upload_path, verbose_name='로고'),
        ),
        migrations.AlterField(
            model_name='customappconfig',
            name='url_nickname',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='URL 별명'),
        ),
    ]
