# Generated by Django 6.0 on 2026-01-01 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_customappconfig_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='회사명')),
                ('business_number', models.CharField(blank=True, default='', max_length=20, verbose_name='사업자번호')),
                ('representative', models.CharField(blank=True, default='', max_length=50, verbose_name='대표자명')),
                ('contact_name', models.CharField(blank=True, default='', max_length=50, verbose_name='담당자 이름')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='담당자 전화번호')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='담당자 이메일')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='주소')),
                ('address_detail', models.CharField(blank=True, default='', max_length=200, verbose_name='상세주소')),
                ('memo', models.TextField(blank=True, default='', verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '그룹',
                'verbose_name_plural': '그룹 목록',
                'ordering': ['-create_time'],
            },
        ),
    ]
