# Generated by Django 6.0 on 2026-01-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='삭제됨'),
        ),
    ]
