# Generated by Django 6.0 on 2026-01-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_group_deleted_at_group_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='그룹 ID'),
        ),
    ]
