# Generated by Django 6.0 on 2026-01-01 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_userprofile_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='전화번호')),
                ('memo', models.CharField(blank=True, default='', max_length=200, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '팀원',
                'verbose_name_plural': '팀원 목록',
                'ordering': ['name'],
            },
        ),
    ]
