# Generated by Django 6.0 on 2026-01-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relay_server',
            field=models.CharField(blank=True, default='admin.787.kr', max_length=100, verbose_name='릴레이 서버'),
        ),
    ]
