# Generated by Django 6.0 on 2026-01-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userprofile_relay_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='relay_server',
            field=models.CharField(blank=True, default='222.239.231.91', max_length=100, verbose_name='릴레이 서버'),
        ),
    ]
