# Generated by Django 6.0 on 2026-01-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_userprofile_relay_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(max_length=100, unique=True, verbose_name='서버 주소')),
                ('server_name', models.CharField(blank=True, default='', max_length=100, verbose_name='서버 이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '릴레이 서버',
                'verbose_name_plural': '릴레이 서버 목록',
                'ordering': ['-create_time'],
            },
        ),
    ]
