# Generated by Django 6.0 on 2026-01-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_relayserver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relayserver',
            options={'ordering': ['-is_default', '-create_time'], 'verbose_name': '릴레이 서버', 'verbose_name_plural': '릴레이 서버 목록'},
        ),
        migrations.AddField(
            model_name='relayserver',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='기본값 여부'),
        ),
    ]
