# Generated by Django 6.0 on 2026-01-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_relayserver_options_relayserver_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayserver',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='퍼블릭 키'),
        ),
    ]
