# Generated by Django 6.0 on 2026-01-07 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_connlog_id_alter_filelog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAuthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='아이디')),
                ('remote_id', models.CharField(blank=True, default='', max_length=50, verbose_name='원격지 ID')),
                ('remote_hostname', models.CharField(blank=True, default='', max_length=100, verbose_name='원격지 호스트명')),
                ('client_ip', models.CharField(blank=True, default='', max_length=50, verbose_name='클라이언트 IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='성공 여부')),
                ('memo', models.CharField(blank=True, default='', max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='인증 시간')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '원격 인증 로그',
                'verbose_name_plural': '원격 인증 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
