# Generated by Django 6.0 on 2026-01-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remoteauthlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdeskDeviceRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=60, verbose_name='원격 ID')),
                ('custom_id', models.CharField(blank=True, default='', max_length=50, verbose_name='사용자 ID')),
                ('agent_id', models.CharField(blank=True, default='', max_length=10, verbose_name='상담원 번호')),
                ('uuid', models.CharField(blank=True, default='', max_length=200, verbose_name='UUID')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='버전')),
                ('hostname', models.CharField(blank=True, default='', max_length=100, verbose_name='호스트명')),
                ('client_ip', models.CharField(blank=True, default='', max_length=50, verbose_name='클라이언트 IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
            ],
            options={
                'verbose_name': 'MDesk 기기 등록',
                'verbose_name_plural': 'MDesk 기기 등록 목록',
                'ordering': ['-updated_at'],
                'unique_together': {('remote_id', 'custom_id')},
            },
        ),
    ]
