# Generated by Django 6.0 on 2026-01-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_mdeskdeviceregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdeskdeviceregistration',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='별칭'),
        ),
        migrations.AddField(
            model_name='mdeskdeviceregistration',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='플랫폼'),
        ),
        migrations.AddField(
            model_name='mdeskdeviceregistration',
            name='user_pkid',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='사용자 고유번호'),
        ),
    ]
