# Generated by Django 6.0 on 2026-01-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_mdeskdeviceregistration_alias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertNoVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, verbose_name='고객 ID')),
                ('mdesk_id', models.CharField(max_length=60, verbose_name='MDesk ID')),
                ('cert_code', models.CharField(max_length=20, verbose_name='인증번호')),
                ('hostname', models.CharField(blank=True, default='', max_length=100, verbose_name='호스트명')),
                ('uuid', models.CharField(blank=True, default='', max_length=200, verbose_name='UUID')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='버전')),
                ('client_ip', models.CharField(blank=True, default='', max_length=50, verbose_name='클라이언트 IP')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 성공 여부')),
                ('verified_at', models.DateTimeField(auto_now_add=True, verbose_name='인증 시간')),
            ],
            options={
                'verbose_name': '인증번호 검증',
                'verbose_name_plural': '인증번호 검증 목록',
                'ordering': ['-verified_at'],
            },
        ),
    ]
