# Generated by Django 6.0 on 2026-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_certno_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_group_admin',
            field=models.BooleanField(default=False, verbose_name='그룹 관리자 여부'),
        ),
    ]
