# Generated by Django 6.0 on 2026-02-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_is_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_2fa',
            field=models.BooleanField(default=False, verbose_name='이메일 2차인증'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_2fa',
            field=models.BooleanField(default=False, verbose_name='휴대전화 2차인증'),
        ),
    ]
