"""
Django settings for rustdesk_server_api project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일에서 환경변수 로드 (로컬 개발용)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass  # python-dotenv가 설치되지 않은 경우 무시
if "CSRF_TRUSTED_ORIGINS" in os.environ:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ["CSRF_TRUSTED_ORIGINS"].split(',')]
else:
    CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:21114"]
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'None'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Docker 환경변수에서 가져옴 (필수 설정)
SECRET_KEY = os.environ.get("SECRET_KEY", 'change-me-in-production')
# ID服务器IP或域名，一般与中继服务器，用于web client
# Docker 환경변수에서 가져옴
ID_SERVER = os.environ.get("ID_SERVER", 'localhost')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", False)
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
ALLOWED_HOSTS = ["*"]
AUTH_USER_MODEL = 'api.UserProfile'      # AppName.自定义user

ALLOW_REGISTRATION = os.environ.get("ALLOW_REGISTRATION", "True")          # 是否允许注册, True为允许，False为不允许
ALLOW_REGISTRATION = True if ALLOW_REGISTRATION.lower() == 'true' else False


# ==========数据库配置 开始=====================
# 데이터베이스 설정 (Docker 환경변수에서 가져옴)
DATABASE_TYPE = os.environ.get("DATABASE_TYPE", 'SQLITE')  # SQLITE, MYSQL, POSTGRESQL
MYSQL_DBNAME = os.environ.get("MYSQL_DBNAME", '')
MYSQL_HOST = os.environ.get("MYSQL_HOST", '')
MYSQL_USER = os.environ.get("MYSQL_USER", '')
MYSQL_PASSWORD = os.environ.get("MYSQL_PASSWORD", '')
MYSQL_PORT = os.environ.get("MYSQL_PORT", '3306')
POSTGRES_DBNAME = os.environ.get("POSTGRES_DBNAME", '')
POSTGRES_HOST = os.environ.get("POSTGRES_HOST", '')
POSTGRES_USER = os.environ.get("POSTGRES_USER", '')
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD", '')
POSTGRES_PORT = os.environ.get("POSTGRES_PORT", '5432')
# ==========数据库配置 结束=====================

LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", 'ko')
# #LANGUAGE_CODE = os.environ.get("LANGUAGE_CODE", 'en')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'webui',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',   # 取消post的验证。
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'api.middleware.TokenAutoLoginMiddleware',  # 토큰 자동 로그인 (AuthenticationMiddleware 이후)
    'api.middleware.AdminSubdomainMiddleware',  # admin.787.kr 접근 제한
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rustdesk_server_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'api.util.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'rustdesk_server_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


# 기본 데이터베이스 설정 (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': POSTGRES_DBNAME,
        'HOST': POSTGRES_HOST,
        'USER': POSTGRES_USER,
        'PASSWORD': POSTGRES_PASSWORD,
        'PORT': POSTGRES_PORT,
    }
}

if DATABASE_TYPE == 'MYSQL' and MYSQL_DBNAME != '-' and MYSQL_USER != '-' and MYSQL_PASSWORD != '-':
    # 简单通过数据库名、账密信息过滤下，防止用户未配置mysql却使用mysql
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': MYSQL_DBNAME,               # 数据库名
            'HOST': MYSQL_HOST,                 # 数据库服务器IP
            'USER': MYSQL_USER,                 # 数据库用户名
            'PASSWORD': MYSQL_PASSWORD,         # 数据库密码
            'PORT': MYSQL_PORT,                 # 端口
            'OPTIONS': {'charset': 'utf8'},
        }
    }
# PostgreSQL은 기본값으로 설정되어 있으므로 조건문 불필요

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = 'static/'

if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')     # 新增

# Media files (업로드된 파일)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 실행파일 저장 경로
EXECUTABLE_DIR = os.path.join(BASE_DIR, 'executables')
EXECUTABLE_TEMPLATE = 'rustdesk_portable-id={username}.exe'  # 템플릿 파일명

LANGUAGES = (
    ('ko', '한국어'),
    ('zh-hans', '中文简体'),
    ('en', 'English'),

)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# ==========이메일 설정 시작 (Docker 환경변수에서 가져옴)=====================
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get("EMAIL_HOST", '')
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", '587'))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", 'True').lower() == 'true'
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", 'False').lower() == 'true'
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", '')
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", '')
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", '')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# ==========이메일 설정 끝=====================

# ==========카카오 알림톡 설정 시작 (Docker 환경변수에서 가져옴)=====================
KAKAO_ALIMTALK_API_URL = os.environ.get("KAKAO_ALIMTALK_API_URL", "")
KAKAO_ALIMTALK_ID = os.environ.get("KAKAO_ALIMTALK_ID", "")
KAKAO_ALIMTALK_PW = os.environ.get("KAKAO_ALIMTALK_PW", "")
KAKAO_ALIMTALK_TEM_NUM = os.environ.get("KAKAO_ALIMTALK_TEM_NUM", "")
KAKAO_ALIMTALK_SEND_NUM = os.environ.get("KAKAO_ALIMTALK_SEND_NUM", "")
# 템플릿 코드는 각 기능별로 하드코딩 (MDTL03: 인증번호, MDTL04: 비밀번호 변경 알림 등)
# ==========카카오 알림톡 설정 끝=====================

